### ISSUE TITLE
The plugin don't work on QGIS 2.18

### ISSUE THREAD

**Issue by CorentinLemaitre** [opengisch/QFieldSync#21]
Hello, 

I have QGIS 2.18 and the plugin is not launched at the begining because there is an error... I don't know if you already heard about it?

**Comment by m-kuhn** [comment]
Yes, we are currently working on the plugin and will make a new release soon. Can you copy/paste the error here, so we can check if it is within the bounds of the next release.

**Comment by m-kuhn** [comment]
@CorentinLemaitre we have just uploaded a new version, can you upgrade this (and the qgis2compat plugin) and report if the situation improved?

**Comment by CorentinLemaitre** [comment]
I have reinstall QGIS2compat and i try to reinstall it from the QGIS plugin manager.
I get this error message : "cannot import name uic" then i have a proposition to desinstall it.

The version that i have download form the plugin manager is 0.8.3, i think it is the last one ?

**Comment by CorentinLemaitre** [comment]
... but i think the situation have improved because it didn't quit my QGIS with a bug.

**Comment by m-kuhn** [comment]
I thought that had been fixed but it seems I forgot something. Can you try version 0.8.4 (will be available now or in the next minutes).

**Comment by CorentinLemaitre** [comment]
I test another time and it seems to work. Thanks!
(I have traduce all i can in french)

**Comment by m-kuhn** [comment]
Merci, je m'ai rendu compte ce matin.
Je pense qu'il manque que un tout petit bout. Est-ce que tu veux que j'attends avec un release avec traduction française?

Je prends la [traduction QGIS](https://www.transifex.com/qgis/QGIS/viewstrings/#fr/qgis-application) pour traduire en allemand normalement (e.g. *map theme* -> *thème de carte*) mais il me semble que juste maintenant la version en ligne ne marche pas.

**Comment by CorentinLemaitre** [comment]
Map theme is badly traduced in some part of qgis in french. In the "composeur d'impression" )print screen?) it is traduced as "réglage de visibilité" I think it is the better way to explain it, or at least it will help some people to improve it ; )La traduction française tu pourras la mettre sur un prochaine version, ce n'est pas pressé. Il faut que d'autres gens participent améliorent aussi.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        De: Matthias KuhnEnvoyé: mardi 29 novembre 2016 09:57À: opengisch/QFieldSyncRépondre à: opengisch/QFieldSyncCc: CorentinLemaitre; MentionObjet: Re: [opengisch/QFieldSync] The plugin don't work on QGIS 2.18 (#21)Merci, je m'ai rendu compte ce matin.
Je pense qu'il manque que un tout petit bout. Est-ce que tu veux que j'attends avec un release avec traduction française?
Je prends la traduction QGIS pour traduire en allemand normalement (e.g. map theme -> thème de carte) mais il me semble que juste maintenant la version en ligne ne marche pas.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opengisch/QFieldSync","title":"opengisch/QFieldSync","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opengisch/QFieldSync"}},"updates":{"snippets":[{"icon":"PERSON","message":"@m-kuhn in #21: Merci, je m'ai rendu compte ce matin.\r\nJe pense qu'il manque que un tout petit bout. Est-ce que tu veux que j'attends avec un release avec traduction française?\r\n\r\nJe prends la [traduction QGIS](https://www.transifex.com/qgis/QGIS/viewstrings/#fr/qgis-application) pour traduire en allemand normalement (e.g. *map theme* -\u003e *thème de carte*) mais il me semble que juste maintenant la version en ligne ne marche pas."}],"action":{"name":"View Issue","url":"https://github.com/opengisch/QFieldSync/issues/21#issuecomment-263512879"}}}

**Comment by m-kuhn** [comment]
"map themes" were called "visibility presets" in QGIS 2.x (because when they started, they were not as powerful as they are nowadays), I guess that's a leftover.
