### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by Oisin-JK** [opengisch/qfieldsync#633]
QGIS version 3.34.15-Prizren
Python version 3.12.8
GDAL/OGR version 3.10.1
OS version Windows 10 Version 2009

QFieldSync plugin won't load. I get the error below. Can anyone advise how I fix this.

> Couldn't load plugin 'qfieldsync' due to an error when calling its classFactory() method 
> 
> AttributeError: module 'osgeo.ogr' has no attribute 'DataSource' 
> Traceback (most recent call last):
>   File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python/plugins\qfieldsync\__init__.py", line 46, in classFactory
>     from qfieldsync.qfield_sync import QFieldSync
>   File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python/plugins\qfieldsync\qfield_sync.py", line 34, in 
>     from qfieldsync.gui.cloud_browser_tree import (
>   File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python/plugins\qfieldsync\gui\cloud_browser_tree.py", line 42, in 
>     from qfieldsync.gui.cloud_projects_dialog import CloudProjectsDialog
>   File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python/plugins\qfieldsync\gui\cloud_projects_dialog.py", line 76, in 
>     from qfieldsync.gui.cloud_transfer_dialog import CloudTransferDialog
>   File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python/plugins\qfieldsync\gui\cloud_transfer_dialog.py", line 29, in 
>     from libqfieldsync.offline_converter import ExportType
>   File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\arbor\AppData\Roaming\QGIS\QGIS3\profiles\Oisin\python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\offline_converter.py", line 50, in 
>     from .offliners import BaseOffliner
>   File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\arbor\AppData\Roaming\QGIS\QGIS3\profiles\Oisin\python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\offliners.py", line 146, in 
>     class PythonMiniOffliner(BaseOffliner):
>   File "C:\Users\arbor\AppData\Roaming\QGIS\QGIS3\profiles\Oisin\python\plugins\qfieldsync\libqfieldsync.whl\libqfieldsync\offliners.py", line 222, in PythonMiniOffliner
>     self, layer: QgsVectorLayer, data_source: ogr.DataSource, offline_gpkg_path: str
>                                               ^^^^^^^^^^^^^^
> AttributeError: module 'osgeo.ogr' has no attribute 'DataSource'
> 
> 
> Python version: 3.12.8 (main, Dec 20 2024, 15:21:15) [MSC v.1938 64 bit (AMD64)] 
> QGIS version: 3.34.15-Prizren Prizren, 386f2583 
> 
> Python Path:
> C:/OSGeo4W/apps/qgis-ltr/./python
> C:/Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python
> C:/Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python/plugins
> C:/OSGeo4W/apps/qgis-ltr/./python/plugins
> C:\OSGeo4W\apps\grass\grass84\etc\python
> C:\WINDOWS\system32
> C:\OSGeo4W\bin\python312.zip
> C:\OSGeo4W\apps\Python312\DLLs
> C:\OSGeo4W\apps\Python312\Lib
> C:\OSGeo4W\bin
> C:\Users\arbor\AppData\Roaming\Python\Python312\site-packages
> C:\OSGeo4W\apps\Python312
> C:\OSGeo4W\apps\Python312\Lib\site-packages
> C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
> C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
> C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
> C:/Users/arbor/AppData/Roaming/QGIS/QGIS3\profiles\Oisin/python
> C:\Users\arbor\AppData\Roaming\QGIS\QGIS3\profiles\Oisin\python\plugins\qfieldsync\libqfieldsync.whl

**Comment by meyerlor** [comment]
I just updated my QGIS-ltr to 3.34.15 via the OSGeo4W Setup and I have now the same problem (previous 3.34.X version was not affected, i can not say though which one i had installed before..) - it's working with QGIS 3.40.3

**Comment by wdlb** [comment]
I have the same problem, my environment is similar to the ones mentioned above, but I'm on Windows 11.

**Comment by m-kuhn** [comment]
Is your GDAL version 3.10?

**Comment by wdlb** [comment]
Yes, 3.10.1 (I don't know if the .1 is important).

![Image](https://github.com/user-attachments/assets/4297f946-76aa-4320-ab37-7d332d6e27c5)

**Comment by Oisin-JK** [comment]
> Is your GDAL version 3.10?

Yes. 3.10.1 too

**Comment by meyerlor** [comment]
(We all probably updated via OSGeo4W? )

**Comment by suricactus** [comment]
Thank you for reporting. I guess all people suffering from the problem are windows users. 

There is a change in one of the dependencies: 

https://github.com/jef-n/OSGeo4W/commit/5469ac4aadc47cab8f535395e6e92c56324d72ef
```
  gdal				3.9.3 -> 3.10.1
```

And we can see in 3.10.0 we had the following change (https://github.com/OSGeo/gdal/blob/v3.10.0/NEWS.md):

> Make ogr.DataSource a synonym of gdal.Dataset

**Comment by suricactus** [comment]
@Oisin-JK @meyerlor @wdlb fix should be delivered with https://github.com/opengisch/qfieldsync/releases/tag/v4.12.2

**Comment by wdlb** [comment]
Thanks a lot for the quick solution!
