### ISSUE TITLE
Configuration window bug

### ISSUE THREAD

**Issue by Martin-GUILLOU** [opengisch/qfieldsync#611]
OS: Windows 11 23h2
    QGIS Version 3.28.15
    QFieldSync Version 4.10.1

When opening the configuration window, the tab appears bugged in the project configuration, 'overprinting' the other tabs.

A python error appears :
              File "C:\Users/...\qfieldsync\qfield_sync.py", line 63, in createWidget
              return ProjectConfigurationWidget(parent)
              File "C:\Users/...\qfieldsync\gui\project_configuration_widget.py", line 127, in __init__
              self.reloadProject()
              File "C:\Users/...\qfieldsync\gui\project_configuration_widget.py", line 170, in reloadProject
              self.mapThemesConfigWidget = MapThemesConfigWidget(
              File "C:\Users/...\qfieldsync\gui\mapthemes_config_widget.py", line 44, in __init__
              self.reload(configuration)
              File "C:\Users/...\qfieldsync\gui\mapthemes_config_widget.py", line 64, in reload
              cmb.setFilters(Qgis.LayerFilter.VectorLayer)
             AttributeError: type object 'Qgis' has no attribute 'LayerFilter'

The 'export for Qfield' function is working fine.

Attached a screenshot of the issue
![PB_QfieldSync_fenetre_parametres](https://github.com/user-attachments/assets/3be5a17f-604d-414a-b976-06000143133e)

**Comment by m-kuhn** [comment]
QGIS versoin 3.28 is end of life, can you update to 3.34?
The `Qgis.LayerFilter` enum did not exist with QGIS 3.28

**Comment by m-kuhn** [comment]
@nirvn @suricactus what's our policy, do we introduce compat changes for 3.28 still (and leave this as a bug) or do we want to increase the minimum version for the plugin to 3.34?

**Comment by Martin-GUILLOU** [comment]
Yep ok, work fine with 3.34.

I'll let you see if you fix this for 3.28 to ensure full backwards compatibility.

Thanks for your great work!
